### ISSUE TITLE
[SUGGESTION] Kick.com VOD Archive Support

### ISSUE THREAD

**Issue by Spectroxx** [OP-Archives/xQc-site#17]
Due to xQc announcing his contract with Kick, is it possible to have VOD archival support for [kick.com/xqc](https://kick.com/xqc ) ?

**Comment by TimIsOverpowered** [comment]
There will need to be a lot of backend changes and frontend changes. Quite a lot of tech work to be done for it to happen.

**Comment by Spectroxx** [comment]
I assumed that would be the case.

I'm not very familiar with how you rip the video stream from Twitch; however, using Kicks API might be a good start.
You can seemingly access the API at [https://kick.com/api/v1/channels/xqc](https://kick.com/api/v1/channels/xqc)

**Comment by dilpicks** [comment]
> There will need to be a lot of backend changes and frontend changes. Quite a lot of tech work to be done for it to happen.

Well tell me how I can help pal
