### ISSUE TITLE
CDN player not playing

### ISSUE THREAD

**Issue by OnyxL** [OP-Archives/xQc-site#24]
![image](https://github.com/user-attachments/assets/72677e53-d93f-47a1-8beb-8ff057ae57e6)

infinite loading in cdn player on every video

**Comment by TimIsOverpowered** [comment]
30e162f3d0dac294ae491f3426ce6cc6c2e797f9 should fix it

**Comment by OnyxL** [comment]
![image](https://github.com/user-attachments/assets/9020f63c-7b85-4782-bed8-40aab5c1f2d0)

now all cdn shows "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Comment by TimIsOverpowered** [comment]
Should be fixed
